dist: trusty
sudo: required

services:
  - docker

script:
  - docker build -t slirp4netns-tests -f Dockerfile.tests .
  - docker run --security-opt seccomp="unconfined" -ti --rm -v /dev:/dev slirp4netns-tests
